### PR TITLE
Assorted cleanup

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by Gankra** [comment]
It's not clear to me the the license files need to be explicitly included. I might have hallucinated hearing that, though.

**Comment by apasel422** [comment]
I can remove and rebase.

**Comment by Gankra** [comment]
@gerv @brson would you be able to provide insight into whether including actual LICENSE files is necessary for a cargo project that specifies the appropriate licenses in its Cargo.toml? In particular we would like to make migration into Rust's std library a totally painless process.

**Comment by gerv** [comment]
Gankro: it depends on what the license is, and how it's being used (e.g. whether it's at the top of each file). BSD licenses require reproduction of the license text; but if it's at the top of each file, it doesn't necessarily need to be in a separate LICENSE file. The Apache license requires a copy of itself to be shipped, IIRC, but Rust already ships one because it's dual-licensed Apache/MIT. 

If you are bringing stuff into Rust's standard library, you really want it to be under Rust's standard license, for simplicity, and the first step should be to talk to the authors to see if you can get that to happen.

If you want more guidance, give more details :-)

**Comment by brson** [comment]
@Gankro For migration of the code, as long as the provenance of the code is clear to a human, and it has the Rust license, I don't anticipate any problems, regardless of how the license is declared.

I do not know whether it is legally sufficient to just put a string like "MIT" at a designated location in the configuration file.

**Comment by Gankra** [comment]
Going full-on seems easiest here, even if it's just cargo-culting.

Thanks, everyone!

**Pull request merged**
